Fix the base image building error due to missing dependency
Original error message:

> WARNING: iot2050-image-base-1.0-r0 do_rootfs_postprocess: Looks like you have ssh host keys in the image but did  not install "sshd-regen-keys". This image should not be  deployed more than once.
> ERROR: iot2050-image-base-1.0-r0 do_rootfs_postprocess: Install the package or forcefully remove this check!
> ERROR: iot2050-image-base-1.0-r0 do_rootfs_postprocess: ExecutionError('/work/build/tmp/work/iot2050-debian-arm64/iot2050-image-base-iot2050/1.0-r0/temp/run.image_postprocess_sshd_key_regen.4785', 1, None, None)
> ERROR: Logfile of failure stored in: /work/build/tmp/work/iot2050-debian-arm64/iot2050-image-base-iot2050/1.0-r0/temp/log.do_rootfs_postprocess.4785
> ERROR: Task (/work/build/../../repo/meta/recipes-core/images/iot2050-image-base.bb:do_rootfs_postprocess) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 201 tasks of which 194 didn't need to be rerun and 1 failed.

Signed-off-by: Baocheng Su <baocheng.su@siemens.com>