meta/images: fix missing dependency for iot2050-image-base
Include the dependent package `sshd-regen-keys` in `iot2050-image-base`
to fix the following build error during rootfs post-processing:

WARNING: iot2050-image-base-1.0-r0 do_rootfs_postprocess: Looks like
you have ssh host keys in the image but did  not install "sshd-regen-keys".
This image should not be  deployed more than once.
ERROR: iot2050-image-base-1.0-r0 do_rootfs_postprocess: Install the package
or forcefully remove this check!
ERROR: iot2050-image-base-1.0-r0 do_rootfs_postprocess: ExecutionError('/work
/build/tmp/work/iot2050-debian-arm64/iot2050-image-base-iot2050/1.0-r0/temp/
run.image_postprocess_sshd_key_regen.171019', 1, None, None)

Signed-off-by: Rakesh Kumar <kumar.rakesh@siemens.com>